// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9aekAhSG313nyRKOFr5L4D7wT2ceH9uA',
    appId: '1:55597762423:web:55488068f64ef5f42a4372',
    messagingSenderId: '55597762423',
    projectId: 'winner-draw-5ad06',
    authDomain: 'winner-draw-5ad06.firebaseapp.com',
    storageBucket: 'winner-draw-5ad06.appspot.com',
    measurementId: 'G-469T18QMVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOPpiueUpeH5i33STSw_0b4KQrCiRB6Tw',
    appId: '1:55597762423:android:00341323fef48ffe2a4372',
    messagingSenderId: '55597762423',
    projectId: 'winner-draw-5ad06',
    storageBucket: 'winner-draw-5ad06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuj1qfhCCgYToAE0d-H7l2J1RkM2YWN2o',
    appId: '1:55597762423:ios:2e6fd1cfaddc3d052a4372',
    messagingSenderId: '55597762423',
    projectId: 'winner-draw-5ad06',
    storageBucket: 'winner-draw-5ad06.appspot.com',
    iosBundleId: 'com.dartsync.drawMaster',
  );
}
